In [1]:
from sentence_transformers import SentenceTransformer

In [14]:
from tqdm.auto import tqdm

In [11]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [12]:
model

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [40]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)

In [42]:
len(v1)

384

In [43]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [44]:
len(dv)

384

In [45]:
v1.dot(dv)

np.float32(0.323324)

In [16]:
q2 = "How to install Docker on Windows?"
v2 = model.encode(q2)

In [17]:
v2.dot(dv)

np.float32(0.019730467)

In [2]:
from ingest import load_faq_data

documents = load_faq_data()

In [51]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [54]:
len(texts)

1350

In [59]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [62]:
vectors[:2]

[array([-2.67062206e-02, -1.22457556e-01,  1.59441885e-02,  6.09419122e-03,
        -1.11915069e-02, -6.55021295e-02, -7.62883723e-02, -2.08820254e-02,
        -9.27567780e-02,  3.55664939e-02,  3.15623283e-02, -1.09016951e-02,
        -2.45336369e-02, -1.82476323e-02,  3.43917087e-02, -1.32052321e-02,
         7.22679589e-03, -1.54126704e-01,  6.41842782e-02, -9.07449052e-03,
         3.94655131e-02, -2.99637765e-02,  2.08512470e-02,  3.71391997e-02,
         3.52526829e-02, -2.49497802e-03,  7.71128982e-02,  2.78048143e-02,
         1.54832397e-02,  4.92820097e-03,  1.48515101e-03,  3.93927395e-02,
         7.25188702e-02,  9.02840868e-02,  5.25653251e-02,  2.72272676e-02,
         3.86085622e-02, -7.50263333e-02, -2.48754695e-02,  1.06018260e-01,
        -4.82870750e-02, -5.00598215e-02, -4.16486301e-02,  7.91618228e-02,
         5.06461635e-02, -3.68630601e-04, -2.83320225e-03, -2.59598438e-02,
        -3.82818393e-02,  8.59545544e-02, -2.85154879e-02, -7.23347068e-02,
        -2.0

In [63]:
import numpy as np
X = np.array(vectors)

In [87]:
X

array([[-0.02670622, -0.12245756,  0.01594419, ..., -0.00230645,
        -0.11218392, -0.02365552],
       [-0.01099556, -0.11074746, -0.02536935, ...,  0.09022225,
        -0.02697366,  0.01975673],
       [-0.08896549, -0.0612818 ,  0.00775604, ...,  0.04059709,
         0.00479281, -0.02745942],
       ...,
       [-0.03652925,  0.01415435, -0.06838642, ...,  0.04316787,
         0.08105537, -0.02148628],
       [-0.1309159 , -0.06990597, -0.00931879, ..., -0.00044343,
        -0.01285731,  0.01426924],
       [-0.07984778,  0.01926991,  0.02544983, ..., -0.0336802 ,
        -0.01884021,  0.05837058]], shape=(1350, 384), dtype=float32)

In [26]:
query = "Can I still join the course after the start date?"
v_query = model.encode(query)

In [27]:
v_query

array([ 2.13904064e-02, -7.39799812e-02,  1.42067927e-03,  2.13816669e-02,
        2.45113149e-02,  3.15582938e-02, -1.10839717e-01, -1.05017461e-01,
       -6.18259013e-02, -6.42311573e-03,  3.72399599e-03,  9.06393304e-02,
       -9.49936919e-03,  6.53976873e-02,  1.10946447e-02, -2.10097190e-02,
       -3.35125439e-02, -4.31677178e-02,  9.96348634e-03,  1.41969668e-02,
       -6.40415475e-02, -7.04179564e-03, -7.91187882e-02,  5.80030754e-02,
        1.30208058e-03,  4.19733115e-03,  5.70979007e-02,  6.39447793e-02,
        2.49902979e-02, -3.95876542e-02, -3.79506610e-02,  2.70394329e-02,
        1.79423466e-02,  1.72272418e-02,  3.43311131e-02,  9.29058064e-03,
        5.86054996e-02, -4.97789495e-02, -5.05370460e-03,  4.34328578e-02,
       -1.56623106e-02, -2.97534652e-02, -5.13326470e-03,  5.13414927e-02,
        6.16064109e-03,  6.86980560e-02, -1.29505387e-02, -5.61938547e-02,
       -1.08265085e-02,  5.96683957e-02,  5.29939942e-02, -3.42755243e-02,
       -4.15273979e-02, -

In [28]:
scores = X.dot(v_query)

In [29]:
scores

array([ 0.4874058 ,  0.20991942,  0.762941  , ..., -0.08637969,
        0.03759794, -0.03037039], shape=(1350,), dtype=float32)

In [30]:
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(2), np.float32(0.762941))

In [31]:
documents[idx]

{'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.",
 'doc_id': '3f1424af17'}

In [32]:
top5 = np.argsort(scores)[-5:]

In [33]:
top5

array([  7, 538, 907, 625,   2])

In [34]:
top5 = top5[::-1]
top5

array([  2, 625, 907, 538,   7])

In [35]:
scores[top5]

array([0.762941  , 0.7579372 , 0.71921325, 0.6536313 , 0.56009996],
      dtype=float32)

In [36]:
for idx in top5:
    print(scores[idx])
    print(documents[idx])
    print()

0.762941
{'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.", 'doc_id': '3f1424af17'}

0.7579372
{'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute.", 'doc_id': '2d8b16c2a0'}

0.71921325
{'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related Questions',

In [88]:
from rag_helper import RAGBase

In [89]:
class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filter_dict = {"course": self.course}

        return self.index.search(
            query_vector,
            num_results=num_results,
            filter_dict=filter_dict
        )

In [90]:
from openai import OpenAI
from dotenv import load_dotenv
import os

groq_base_url = "https://api.groq.com/openai/v1"
load_dotenv()

openai_client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url=groq_base_url
)

In [91]:
vector_assistant = RAGVector(
    embedder=model,
    index=vindex,
    llm_client=openai_client,
)

In [69]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vindex.search(
    query_vector,
    filter_dict={"course": "llm-zoomcamp"},
    num_results=5
)

In [92]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [70]:
results

[{'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
  'doc_id': '74eb249bbf'},
 {'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'Certificate: Can I follow the course in a self-paced mode and get a certificate?',
  'answer': 'No, you can only get a certificate if you finish the course with a "live" cohort.\n\nWe don\'t award certificates for the self-paced mode. The reason is you need to peer-review 3 capstone(s) after submitting your project.\n\nYou can only peer-review projects at the time the course is running; after the form is closed and the peer-review list is compiled.',
  'doc_id': '69d122f12e'},
 {'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'When will the course be offere

In [93]:
vector_assistant.rag("the program has already begun, can I still sign up?")

NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-5.4-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'code': 'model_not_found'}}